name: Generate Snake

permissions:
  contents: write  # garante que o token possa escrever no branch output

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: AlaneOliveira
          outputs: |
            dist/github-contribution-grid-snake.svg
          background: "#000000"  # fundo preto
          snake: "#A259FF"       # cor da cobrinha lilás
          stroke: "#FFFFFF"      # borda da cobrinha opcional
          cell_size: 12          # tamanho do quadrado
          cell_padding: 4        # espaçamento entre quadrados

      - name: Push Snake Animation
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
